### ISSUE TITLE
Automatic messages are not delivered to the group 

### ISSUE THREAD

**Issue by farexgit** [metalmatze/alertmanager-bot#10]
Automatic messages are not delivered to the group of telegrams about the active alert
If I interrogate the bot with the / alert command then the message comes up.
What could be the reason?

sorry for my English

**Comment by metalmatze** [comment]
If I get this correctly you're trying to say: When you send `/alerts` it answers you directly in a direct and private message?

I just tested that locally. This seems to be the case and is definitely a bug. I will push a fix very soon.

**Comment by metalmatze** [comment]
I finally got the time to tag the release. This should resolve your problem, please update.
https://github.com/metalmatze/alertmanager-bot/releases/tag/0.2.1

**Comment by farexgit** [comment]
Thank you very much.
