### ISSUE TITLE
Error: status code is 405 not 200 when I execute commands /status /alerts

### ISSUE THREAD

**Issue by abashkinas** [metalmatze/alertmanager-bot#102]
Hello, when I execute the commands /status /alerts, I get errors (screen in the attachment)

![screen](https://user-images.githubusercontent.com/49237188/75687365-c0fb9700-5cae-11ea-9993-9589331c8480.png)

The following errors in the logs:

[logs.txt](https://github.com/metalmatze/alertmanager-bot/files/4275987/logs.txt)

Please tell me what could be the problem ?:

**Comment by metalmatze** [comment]
Seems like the URL to connect to Alertmanager is wrong: `url=http://localhost:8080/api/v1/alerts`.
Is there really Alertmanager running on localhost:8080? Most likely something else :)

**Comment by abashkinas** [comment]
Yes, you're right, thanks :)

**Comment by metalmatze** [comment]
Closing then :blush:
