### ISSUE TITLE
k8s install error

### ISSUE THREAD

**Issue by DevOpserzhao** [metalmatze/alertmanager-bot#119]
Warning  FailedCreate      3s (x20 over 16m)  statefulset-controller  create Pod alertmanager-bot-0 in StatefulSet alertmanager-bot failed error: Pod "alertmanager-bot-0" is invalid: spec.containers[0].env[1].valueFrom.secretKeyRef.name: Invalid value: "xxxxx:xxxx": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by metalmatze** [comment]
The name of your secret is not allowed. It's name needs to be ` 'a-z0-9?(.a-z0-9?)*'`.

**Comment by DevOpserzhao** [comment]
> The name of your secret is not allowed. It's name needs to be ` 'a-z0-9?(.a-z0-9?)*'`.

thinks,  i have solved the problem

**Comment by DevOpserzhao** [comment]
thinks, i have solved the problem
