### ISSUE TITLE
server misbehaving

### ISSUE THREAD

**Issue by prgomes** [metalmatze/alertmanager-bot#121]
I am getting this message and the docker container ramains  restarting. Whats could be?

**Comment by prgomes** [comment]
level=error ts=2020-06-27T02:48:49.053559454Z caller=main.go:215 component=telegram msg="failed to create bot" err="http.Post failed: Post https://api.telegram.org/bot10266232772:AAGTm2yOrDb77ipRBcEr_B6k2a5MUP7DDD/getMe: dial tcp: lookup api.telegram.org on 127.0.0.11:53: server misbehaving"

**Comment by metalmatze** [comment]
Your DNS server is unable to resolve api.telegram.org. This is not an issue with the bot, but with your general environment.

**Comment by metalmatze** [comment]
I just realized: You've posted your Telegram token. You need to generate a new one to make the one you posted invalid!
