### ISSUE TITLE
Starting alertmanager-bot

### ISSUE THREAD

**Issue by kdsystem** [metalmatze/alertmanager-bot#124]
Please add info into README that you need exactly type "/start" command to the bot when alertmanager-bot is running and awaiting commands.
So this "start" command is not for BotFather, but exactly for already running bot in Docker or etc.
Thank you.
(waisted 3 days to understand that)

**Comment by metalmatze** [comment]
Happy to add this, although that's literally the same with every other Telegram bot too.
