### ISSUE TITLE
Bot Not Starting

### ISSUE THREAD

**Issue by gatotsayogya** [metalmatze/alertmanager-bot#136]
`level=error ts=2020-11-28T17:51:40.752119262Z caller=main.go:215 component=telegram msg="failed to create bot" err="http.Post failed: Post https://api.telegram.org/<TOKEN>/getMe dial tcp: lookup api.telegram.org on 127.0.0.11:53: read udp 127.0.0.1:56783->127.0.0.11:53: i/o timeout"`

I am getting this message in last docker logs Whats could be?

**Comment by gatotsayogya** [comment]
`dial tcp: lookup api.telegram.org on 127.0.0.11:53: read udp 127.0.0.1:57600-\u003e127.0.0.11:53: i/o timeout\"\n","stream":"stderr","time":"2020-11-28T18:21:55.414933957Z"}`

sorry, this is rest complete log text

**Comment by morremeyer** [comment]
This looks like a problem with your DNS resolution as the queries to `127.0.0.11:53` are timing out.

Can you verify if your DNS resolution is working and then recheck this?

**Comment by gatotsayogya** [comment]
I've added 53/udp and and 57600/udp to my firewalld centos, but not solved. Then I turn off my firewalld, that solved that problem. Maybe I had wrong setup to my firewald. Thank you
