### ISSUE TITLE
Release 0.4.3

### ISSUE THREAD

**Issue by PabloCastellano** [metalmatze/alertmanager-bot#137]
Dear @metalmatze, could you release 0.4.3 with the current code available in master?

In the meantime, I have done it myself in my own docker hub account: https://hub.docker.com/repository/docker/pablocastellano/alertmanager-bot/

Thanks in advance!

**Comment by metalmatze** [comment]
I've tagged and pushed 0.4.3!

Find the changelog and binaries here:
https://github.com/metalmatze/alertmanager-bot/releases/tag/0.4.3
Docker images has been pushed too:
https://hub.docker.com/r/metalmatze/alertmanager-bot/tags?page=1&ordering=last_updated
