### ISSUE TITLE
chat_id in variables

### ISSUE THREAD

**Issue by vankosa** [metalmatze/alertmanager-bot#155]
Why not make a variable, for example CHAT_ID, to define chats the same way as admins (with multiple values) without using a storage backend? It is not always possible to persistently store data.

**Comment by metalmatze** [comment]
That won't work, because once the `/start` the bot fetches extra data from the Telegram API which it needs to contact the user once a message has to be sent.

**Comment by vankosa** [comment]
Does this somehow interfere with storing chat id in variables instead of a database?

**Comment by metalmatze** [comment]
The  ChatID is just some sort of bad access control for the initial admin to check if that user is actually allowed.
Everything else needs more state from the Telegram API and is initialized through the `/start` command.
