### ISSUE TITLE
does not send to group chat

### ISSUE THREAD

**Issue by belogolovm** [metalmatze/alertmanager-bot#198]
Hello! Help, please... 
Everything works if I put TELEGRAM_ADMIN on my id, but if  I put the group chat is "-xxxx" then messages do not come and the bot does not respond in group chat to /status@mybot

Am I specifying the variable correctly?

  alertmanager-bot:
    command:
    - --alertmanager.url=http://alertmanager:9093
    - --log.level=info
    - --store=bolt
    - --bolt.path=/data/bot.db
    environment:
      TELEGRAM_ADMIN: "-xxxxx"
      TELEGRAM_TOKEN: xxxxx
    image: metalmatze/alertmanager-bot:0.4.3
    networks:
    - monitoring
    ports:
    - 8080:8080
    restart: always
    volumes:
    - ./data:/data

**Comment by belogolovm** [comment]
I read and understood that only admin user should be in this variable. And so, I created a new bot, created a new chat, added the bot to administrators, indicated its token in the config, indicated my id and no notifications

![image](https://user-images.githubusercontent.com/49549322/145987499-61cdeda0-5dd7-464e-a0a6-9da020701b6f.png)

**Comment by metalmatze** [comment]
The admin is an actual user account. Meaning, that would be you with your own account to control some admin aspects of the bot.

**Comment by belogolovm** [comment]
> The admin is an actual user account. Meaning, that would be you with your own account to control some admin aspects of the bot.

I get it, thanks! But the problem is not solved, the bot ignores the chat, it was added to the chat by the administrator, but it does not listen to commands. And when I write to him /start, he sends only to me, not to the chat

**Comment by belogolovm** [comment]
Thank! The problem turned out to be that I was creating a channel, not a group.
