### ISSUE TITLE
Receive alerts after restart alertmanager

### ISSUE THREAD

**Issue by Kerber0ss** [metalmatze/alertmanager-bot#202]
Hi, after restart alertmanager\prometheus telegram bot did not receive alerts, always must be entered /start at bot for initiate it.
error in logs: failed to get chat list from store" err="Key not found in store"
Is it possible to somehow get rid of this so that the bot automatically receives alerts after restarting the services?f

**Comment by metalmatze** [comment]
Hey.
No, that's a limitation of Telegram. You have to contact a bot first and then it can send you messages. Otherwise random Bots could start spamming everyone.
I hope that helps.

**Comment by Kerber0ss** [comment]
I connect my bot to grafana. And now i restart my docker continers with prometheus/alertmanager/etc services and go to grafana - press test and i receive alert to telegram.
At alertmanager-bot i cant receive alert after restart my services, i need type /start every time when i shutdown and start alertmanager-bot. Why?

**Comment by metalmatze** [comment]
In that case you're probably missing persistence for the bot. So adding a volume for the data will help. In there the chats are stored, so that after a restart the bot can still message these chats.

**Comment by Kerber0ss** [comment]
Thats great! all works!
Tell me please about format message: Duration line at alert now: Duration -
Why?
And how to change FIRING to other word?
