### ISSUE TITLE
Style of sending the text of the bot how to connect (alertmanager)

### ISSUE THREAD

**Issue by sandr30** [metalmatze/alertmanager-bot#33]

**Comment by metalmatze** [comment]
Templating of messages was just merged into `master` less than 24 hours ago.
We yet have to create a release with that feature.

**Comment by metalmatze** [comment]
@sandr30 You just posted your Telegram token to the public. Please delete that with the BotFather and create a new token for your bot.

**Comment by metalmatze** [comment]
Just as a note: Deleting the message doesn't help as everybody still can see the message in the history and might already have seen it (like me). So make sure to generate a completely new one.
