### ISSUE TITLE
error send test message

### ISSUE THREAD

**Issue by kolesnikovIV** [metalmatze/alertmanager-bot#36]
for some reason whent try ./example/webhooks/firing.sh
i got error:

> level=error ts=2018-11-21T10:20:32.887277006Z caller=bot.go:159 msg="failed to get chat list from store" err="Key not found in store"

what it means and how to fix it ?

i'm running this container with command:
`docker run   -e 'ALERTMANAGER_URL=http://alertmanager:9093'  -e 'BOLT_PATH=/data/bot.db'     -e 'STORE=bolt'  -e 'TELEGRAM_ADMIN=-XXXX'     -e 'LISTEN_ADDR=0.0.0.0:8080'        -e 'TELEGRAM_TOKEN=XXXX:XXXXXXXX'     -p 8080:8080       metalmatze/alertmanager-bot:0.3.1`

**Comment by metalmatze** [comment]
You need to write the bot `/start` first, so it has your user stored in the database.
That needs to happen before being able to send alerts via webhooks, as webhooks are not yet associated with Telegram users and thus need a look up in the database.

**Comment by ranierigarcia** [comment]
How can I do that? "write the bot /start first"

**Comment by metalmatze** [comment]
![Screenshot from 2019-10-31 13-53-34](https://user-images.githubusercontent.com/872251/67948366-dae47a80-fbe5-11e9-92c4-5a23146813ac.png)

**Comment by ranierigarcia** [comment]
I started the bot. Is TELEGRAM_ADMIN the same as chat_id? I'm getting this error:
level=error ts=2019-10-31T12:10:30.838986706Z caller=bot.go:277 component=telegram msg="failed to get chat list from store" err="Key not found in store"
I'm trying to send messages to a telegram group. Thanks for your attention.
