### ISSUE TITLE
certificate problem

### ISSUE THREAD

**Issue by marfich** [metalmatze/alertmanager-bot#41]
Hello!
When trying to run my container:
```
docker run -d -e 'ALERTMANAGER_URL=http://myip:9093' -e 'BOLT_PATH=/data/bot.db'  
-e 'STORE=bolt' -e 'TELEGRAM_ADMIN=my telegram account id'  
-e 'TELEGRAM_TOKEN=my token copied from BotFather' 
-e 'LISTEN_ADDR=0.0.0.0:8080' -v 'alertmanager-bot_data:/data'  
--name alertmanager-bot metalmatze/alertmanager-bot:0.3.1
```
I get the following error in logs and container stops:
```
level=error ts=2018-12-19T19:17:42.825261817Z caller=main.go:176 component=telegram 
msg="failed to create bot" err="http.Post failed: Post https://api.telegram.org/botMYTOKEN/getMe: 
x509: certificate is not valid for any names, but wanted to match api.telegram.org"
```

Would you be so kind to tell me: what certificate is it talking about? Do I need a client certificate or maybe there is a problem on server side?

**Comment by metalmatze** [comment]
Does the problem still exist?
To me this looks like a problem telegram had with their certificates.

**Comment by metalmatze** [comment]
Feel free to reopen, if the problem still exists. Closing for now.

**Comment by armanzhakypbayev** [comment]
Hello @marfich did you solve this problem? I faced the same issue, cant resolve this!

**Comment by armanzhakypbayev** [comment]
could you @metalmatze help me!
