### ISSUE TITLE
Ansible role for installation

### ISSUE THREAD

**Issue by mbaran0v** [metalmatze/alertmanager-bot#42]
Hi @metalmatze ! Thank you for you project.

I use your alertmanager-bot in my systems - it's amazing. For convenience, I wrote ansible role (https://www.ansible.com) for installation and configuration - https://github.com/mbaran0v/ansible-role-alertmanager-bot

i just inform you about it (you can add link in your readme.md, or not add)

Thank you

**Comment by metalmatze** [comment]
Hey. That's very cool!
Would you mind creating a PR and put it into the README as you wish?

Thanks!

**Comment by mbaran0v** [comment]
Hey! I am create PR https://github.com/metalmatze/alertmanager-bot/pull/64
