### ISSUE TITLE
json error in docker container

### ISSUE THREAD

**Issue by laurenzgamper** [metalmatze/alertmanager-bot#5]
First thanks for the bot, it's awesome!

When I run the program using the latest master everything works fine, and when I run the docker container from https://hub.docker.com/r/metalmatze/alertmanager-bot/ I get the following error:

`level=warn ts=2017-10-11T15:00:37.860944208Z caller=webhook.go:38 msg="failed to decode webhook message" err="json: cannot unmarshal string into Go struct field WebhookMessage.groupKey of type uint64"`

And the webhook function does not work. The reason is probably an outdated github.com/prometheus/alertmanager/notify . It would be awesome if you update the container.

**Comment by metalmatze** [comment]
Hey, thanks for reporting! 
I'm currently working on the project again, after a few months. I've updated the vendored dependencies. I've also added proper group chat support and storage via boltdb or consul.
I want to do a few more things, but then I'm releasing v0.2.

Maybe you can try building a container from the current master? 
Cheers!

**Comment by laurenzgamper** [comment]
Thanks for the answer, did find a solution that works
Cheers!
