### ISSUE TITLE
cant get the bot the run

### ISSUE THREAD

**Issue by yctn** [metalmatze/alertmanager-bot#50]
i downloaded the source and builded it so far so good,

but when i run it i get the following error:
./alertmanager-bot --alertmanager.url=http://127.0.0.1:9093 --store=bolt --telegram.admin=MYID --telegram.token=MYTOKEN --listen.addr http://127.0.0.1:9094 --bolt.path=/tmp/bolt.db --template.paths=./default.tmpl

level=error ts=2019-02-04T13:59:53.153842038Z caller=main.go:213 component=telegram msg="failed to create bot" err="api error: Not Found"

what could this be?

**Comment by metalmatze** [comment]
This reads like you can't access the Telegram APi

**Comment by metalmatze** [comment]
Closing, feel free to reopen, if the problem still exists
