### ISSUE TITLE
Docker image v0.4.0 failing to start due to missing templates

### ISSUE THREAD

**Issue by zackpollard** [metalmatze/alertmanager-bot#54]
Watchtower recently updated my alertmanager-bot image and since then my bot has failed to start. I rolled back manually to 0.3.1 and this has fixed that for now. Looking through the 0.4.0 changes and the errors i'm receiving in the console, it looks like the docker image is checking for templates in the default location of ./default.tmpl however it should be loading from /templates/default.tmpl. When I provided the environment variable and manually changed the location to /templates/default.tmpl, the bot starts. I haven't got time right now to look through the code to find why exactly this isn't being set correctly, however maybe a default needs to be set for that environment variable in the dockerfile so that it overrides the location of ./default.tmpl as otherwise the bot will not start without setting that manually.

**Comment by zackpollard** [comment]
The error that is received when you don't specify the environment variable is as follows:
```error parsing commandline arguments: path './default.tmpl' does not exist```

**Comment by mfominov** [comment]
add variable TEMPLATE_PATHS with temlate location
default template location:
-e "TEMPLATE_PATHS=/templates/default.tmpl"

**Comment by zackpollard** [comment]
@mfominov Yea, I got it working using that, however that should be a default, not something we have to implicitly add in order for it to work. As you said, it is the "default" yet it does not default to that location currently.
