### ISSUE TITLE
can't using command for many people 

### ISSUE THREAD

**Issue by anphn** [metalmatze/alertmanager-bot#62]
When i add bot to groups. Only me can using command to bot. Everybody in my group cant do it

**Comment by metalmatze** [comment]
Yes. Every user that is able to interact with the bot at the moment needs to be an admin, as everyone able to access the bot is able to do everything.
https://github.com/metalmatze/alertmanager-bot#authentication

**Comment by anphn** [comment]
> Yes. Every user that is able to interact with the bot at the moment needs to be an admin, as everyone able to access the bot is able to do everything.
> https://github.com/metalmatze/alertmanager-bot#authentication

thank you babe!!....

**Comment by metalmatze** [comment]
You're welcome, but that's not really appropriate:
> thank you babe!!....

**Comment by anphn** [comment]
> You're welcome, but that's not really appropriate:
> 
> > thank you babe!!....

oh sorry just fun :D.
