### ISSUE TITLE
health check url

### ISSUE THREAD

**Issue by runningman84** [metalmatze/alertmanager-bot#66]
Does the bot provide some kind of health check url? It would be great if I could include that in my kubernetes deployment...

**Comment by runningman84** [comment]
it looks like there is an undocumented url already in the code:
m.HandleFunc("/health", handleHealth)

**Comment by metalmatze** [comment]
Yes, correct. 
It will simply return 200 OK and indicate the the web server receiving the notifications from Alertmanager is up.

https://github.com/metalmatze/alertmanager-bot/blob/f492181c8cd5f94a06aee656711db20a86ecd466/cmd/alertmanager-bot/main.go#L236-L238
