### ISSUE TITLE
not compile

### ISSUE THREAD

**Issue by bimw520** [metalmatze/alertmanager-bot#68]
Hi, have some problem, 
go version go1.10.3 gccgo (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0 linux/amd64

github.com/metalmatze/alertmanager-bot/pkg/alertmanager

../go/src/github.com/metalmatze/alertmanager-bot/pkg/alertmanager/webhook.go:14:83: error: reference to undefined identifier ‘notify.WebhookMessage’
 func HandleWebhook(logger log.Logger, counter prometheus.Counter, webhooks chan<- notify.WebhookMessage) http.HandlerFunc {
^
../go/src/github.com/metalmatze/alertmanager-bot/pkg/alertmanager/webhook.go:27:15: error: reference to undefined identifier ‘notify.WebhookMessage’                                                                                                                                   
                                                      ^
var webhook notify.WebhookMessage

**Comment by metalmatze** [comment]
You need to use Go 1.11 and above as this project relies on Go Modules. When you've updated run `export GO111MODULE=on` and try compiling again. 
For each release we also provide binaries.

**Comment by bimw520** [comment]
thank's.
