### ISSUE TITLE
problem with syntax for template

### ISSUE THREAD

**Issue by bimw520** [metalmatze/alertmanager-bot#69]
Hi
🔥 FIRING 🔥
telegram.default 

Duration: 8 minutes

at alertmanager 0.17.0 the probably change syntax 
In tamplate {{ .Annotations.message }} not work They are change to {{ .Annotations.summary }}
{{ .Annotations.description }} is work.
;)

**Comment by metalmatze** [comment]
Those annotation depend on what ever your alerts are configured to use. They don't change with the Alertmanager version. If you use the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) for example, that projects uses the `annotations.message`.

You can adjust all of that with the build in templating of the alertmanager-bot.

**Comment by bimw520** [comment]
thanks
