### ISSUE TITLE
How to makee existing bot to send messages to existing chat

### ISSUE THREAD

**Issue by Andrusha26** [metalmatze/alertmanager-bot#75]
I've already had a bot and chat. I need to make existing bot sends alerts via your app. How can I achieve this? Because now, I don't really understand why I have to specify adminId, and where your app gets chatId?

There is the same closed issue #3, but, where I should to put user.yml? what kind of template users.yml have to have, where I should pass it in docker-compose volume?

**Comment by metalmatze** [comment]
All you need is the token of your bot and put that into the configuration. The AdminID is currently the way to specificy the allowed users that are able to talk to the bot. You can find that invarious ways. It's your ID on Telegram, if you want to be the admin.

**Comment by Andrusha26** [comment]
> All you need is the token of your bot and put that into the configuration. The AdminID is currently the way to specificy the allowed users that are able to talk to the bot. You can find that invarious ways. It's your ID on Telegram, if you want to be the admin.

Okay, I can specify bot id, but what about adminId, should I specify all users are currently in chat??? I only need bot sends alerts to some chat, and I only have the chat Id. I don't want to get id of all users in chat. There are no possible ways to achieve my goal(make the bot to send alerts into the chat, by chatId)??

**Comment by metalmatze** [comment]
Adding the bot to the group should work just fine and everyone is going to be able to see message. Only admins are allowed to interact with the bot.

**Comment by Andrusha26** [comment]
> Adding the bot to the group should work just fine and everyone is going to be able to see message. Only admins are allowed to interact with the bot.

So where I can specify to which chat bot need to send alert???? I see that as follow: some alert is occurred, and was handled by the manager, which notifies alertmanager-bot, but how does the bot know, in what chat to append alert??? There is no word about specifying of chatId

**Comment by metalmatze** [comment]
Once you have added the admin IDs in the configuration and added the bot to your group, one of the admins is able to write `/start` into the chat and active sending messages there.

**Comment by Andrusha26** [comment]
oh okay, will try, thank you so mush)
