### ISSUE TITLE
Defaults not respected

### ISSUE THREAD

**Issue by ThreeFx** [metalmatze/alertmanager-bot#87]
The README specified that both `alertmanager.url` and `listen.addr` are populated with default values, however downloading the latest release (0.4.0 at time of writing) requires the user to specify both variables.

What is the intended behaviour?

**Comment by metalmatze** [comment]
Thank you for reporting. They were probably removed by accident. I brought them back, however they aren't in a release yet.
I might just cut 0.4.1 now.

**Comment by ThreeFx** [comment]
Looks like they're released now. Thanks for fixing that!
